### ISSUE TITLE
Auto Complete Scrollbar is not working in Bootstrap Modal dialog

### ISSUE THREAD

**Issue by powercoder23** [reactjs/react-autocomplete#136]
Hi,

When i was trying to put this Auto-complete in the Modal dialog, the scrollbar is not working. 

In side the dialog the behavior is, when we try to grab the scrollbar the menu disappears, and i see a error in my console 

`React.findDOMNode` is not a function.

Can you please help me whether i am doing anything wrong, I have just taken this example inside a modal dialog [https://reactcommunity.org/react-autocomplete/custom-menu/](url)

Thanks,
Dhiraj Gupta

**Comment by CMTegner** [comment]
Hi! This was fixed in 579eaa, but we haven't released a new version on npm yet. You can follow the [1.0.x milestone](https://github.com/reactjs/react-autocomplete/milestone/3) to see how we're doing.

**Comment by powercoder23** [comment]
Hi @CMTegner ,

I took the 579eaa, i can see the changes but the issue still existing, when I try to scroll the list, the list is closed only in the modal dailog

Thanks,
Dhiraj

**Comment by CMTegner** [comment]
I know it's been a while, but I wanted to see if you're still experiencing this problem. We've cut a few releases since last we spoke, if you haven't already I would highly suggest updating to the latest version of react-autocomplete.

**Comment by powercoder23** [comment]
Actually, i was able to make it work by removing the tab index from the bootstrap modal, but thank you for the update, we will try to update to the latest version

cheers!!
